'use strict';
const fs = require('fs'); const prisma = require('../services/dbService'); const storage = require('../services/libraryStorage'); const logger = require('../services/logger');
const TYPES={'.pdf':['application/pdf'],'.ppt':['application/vnd.ms-powerpoint'],'.pptx':['application/vnd.openxmlformats-officedocument.presentationml.presentation'],'.doc':['application/msword'],'.docx':['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],'.xls':['application/vnd.ms-excel'],'.xlsx':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],'.png':['image/png'],'.jpg':['image/jpeg'],'.jpeg':['image/jpeg'],'.gif':['image/gif']}; const MAX_BYTES=Number(process.env.LIBRARY_MAX_UPLOAD_BYTES||25*1024*1024); const nil=v=>(v==null||String(v).trim()===''||String(v).toUpperCase()==='ALL')?null:String(v).trim();
function data(b){return {title:String(b.title||'').trim(),description:nil(b.description),category:String(b.category||'GENERAL').trim().toUpperCase(),subject:nil(b.subject),branch:nil(b.branch),semester:nil(b.semester),section:nil(b.section),academicYear:nil(b.academicYear)}}
function allowed(m,s){return(!m.branch||m.branch===s.branch)&&(!m.semester||m.semester===s.semester)&&(!m.section||m.section===s.section)&&(!m.academicYear||m.academicYear===s.academicYear||m.academicYear===s.year)}
async function notify(m){try{const w={};if(m.branch)w.branch=m.branch;if(m.semester)w.semester=m.semester;if(m.section)w.section=m.section;if(m.academicYear)w.OR=[{academicYear:m.academicYear},{year:m.academicYear}];const ss=await prisma.student.findMany({where:w,select:{id:true}});await prisma.notification.createMany({data:ss.map(s=>({studentId:s.id,title:`New ${m.subject||'E-Library'} material uploaded: ${m.title}`,message:'Open E-Library to view or download it.',type:'library',category:'update',date:new Date().toISOString(),metadata:JSON.stringify({materialId:m.id})})),skipDuplicates:true})}catch(e){logger.warn(`[Library] notification delivery failed: ${e.message}`)}}
async function upload(req,res,next){try{if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'A file body is required.'});if(req.body.length>MAX_BYTES)return res.status(413).json({error:'File exceeds upload limit.'});const originalFileName=storage.safeName(req.headers['x-file-name']);const ext=storage.extension(originalFileName);if(!TYPES[ext])return res.status(400).json({error:'Unsupported file extension.'});const detected=storage.detectType(req.body,ext);if(!detected)return res.status(400).json({error:'File signature does not match a supported academic file.'});if(!TYPES[ext].includes(req.headers['content-type'])&&req.headers['content-type']!=='application/octet-stream')return res.status(400).json({error:'Declared MIME type does not match extension.'});const d=data(req.query);if(!d.title)return res.status(400).json({error:'title is required.'});const stored=await storage.save(req.body,originalFileName);let m=await prisma.libraryMaterial.create({data:{...d,...stored,originalFileName,fileType:ext.slice(1).toUpperCase(),mimeType:detected,fileSize:req.body.length,uploadedBy:req.admin.email,uploadedByRole:req.admin.role}});m=await prisma.libraryMaterial.update({where:{id:m.id},data:{fileUrl:`/api/library/materials/${m.id}/content`}});setImmediate(()=>notify(m));res.status(201).json({success:true,material:m})}catch(e){next(e)}}
async function studentList(req,res,next){try{const s=await prisma.student.findUnique({where:{id:req.user.id}});if(!s)return res.status(401).json({error:'Student session is not valid'});const q=String(req.query.q||'').trim(),and=[{OR:[{branch:null},{branch:s.branch}]},{OR:[{semester:null},{semester:s.semester}]},{OR:[{section:null},{section:s.section}]},{OR:[{academicYear:null},{academicYear:s.academicYear},{academicYear:s.year}]}];if(q)and.push({OR:[{title:{contains:q,mode:'insensitive'}},{subject:{contains:q,mode:'insensitive'}},{category:{contains:q,mode:'insensitive'}}]});if(req.query.subject)and.push({subject:String(req.query.subject)});if(req.query.category)and.push({category:String(req.query.category).toUpperCase()});res.json(await prisma.libraryMaterial.findMany({where:{isActive:true,AND:and},orderBy:{createdAt:'desc'}}))}catch(e){next(e)}}
async function adminList(req,res,next){try{const where={};if(req.query.q)where.OR=[{title:{contains:String(req.query.q),mode:'insensitive'}},{subject:{contains:String(req.query.q),mode:'insensitive'}}];res.json(await prisma.libraryMaterial.findMany({where,orderBy:{createdAt:'desc'}}))}catch(e){next(e)}}
async function update(req,res,next){try{const d=data(req.body);if(!d.title)delete d.title;res.json({success:true,material:await prisma.libraryMaterial.update({where:{id:req.params.id},data:d})})}catch(e){next(e)}}
async function archive(req,res,next){try{res.json({success:true,material:await prisma.libraryMaterial.update({where:{id:req.params.id},data:{isActive:false}})})}catch(e){next(e)}}
async function del(req,res,next){try{const m=await prisma.libraryMaterial.delete({where:{id:req.params.id}});await storage.remove(m.fileName);res.json({success:true})}catch(e){next(e)}}
async function replaceFile(req,res,next){try{if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'A file body is required.'});if(req.body.length>MAX_BYTES)return res.status(413).json({error:'File exceeds upload limit.'});const originalFileName=storage.safeName(req.headers['x-file-name']);const ext=storage.extension(originalFileName);if(!TYPES[ext])return res.status(400).json({error:'Unsupported file extension.'});const detected=storage.detectType(req.body,ext);if(!detected)return res.status(400).json({error:'File signature does not match a supported academic file.'});const m=await prisma.libraryMaterial.findUnique({where:{id:req.params.id}});if(!m)return res.status(404).json({error:'Material not found'});const stored=await storage.save(req.body,originalFileName);await storage.remove(m.fileName);const updated=await prisma.libraryMaterial.update({where:{id:m.id},data:{fileName:stored.fileName,originalFileName,fileType:ext.slice(1).toUpperCase(),mimeType:detected,fileSize:req.body.length}});res.json({success:true,material:updated})}catch(e){next(e)}}
async function serve(req,res,next){try{const m=await prisma.libraryMaterial.findUnique({where:{id:req.params.id}});if(!m||!m.isActive)return res.status(404).json({error:'Material not found'});const s=await prisma.student.findUnique({where:{id:req.user.id}});if(!s||!allowed(m,s))return res.status(403).json({error:'You are not authorized to access this material'});await prisma[req.query.download==='true'?'libraryDownload':'libraryView'].upsert({where:{studentId_materialId:{studentId:s.id,materialId:m.id}},update:{},create:{studentId:s.id,materialId:m.id}});const file=storage.resolve(m.fileName);if(!fs.existsSync(file))return res.status(404).json({error:'Stored file is unavailable'});res.type(m.mimeType);res.setHeader('Content-Disposition',`${req.query.download==='true'?'attachment':'inline'}; filename="${m.originalFileName.replace(/[\r\n"]/g,'_')}"`);fs.createReadStream(file).on('error',next).pipe(res)}catch(e){next(e)}}
module.exports={upload,studentList,adminList,update,archive,del,serve,replaceFile};
