tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        "colors": {
                "surface-variant": "#e1e2e8",
                "surface-bright": "#faf9fc",
                "primary-container": "#e4e2e1",
                "on-secondary": "#fff6ff",
                "secondary-fixed-dim": "#e5caff",
                "on-secondary-fixed": "#4f3170",
                "inverse-primary": "#ffffff",
                "on-surface-variant": "#5c5f64",
                "surface-dim": "#d8dae0",
                "surface": "#faf9fc",
                "outline-variant": "#b0b2b7",
                "surface-container-high": "#e7e8ed",
                "tertiary-fixed-dim": "#ec96a1",
                "on-tertiary-fixed-variant": "#6c2d37",
                "error-container": "#f76a80",
                "on-error-container": "#68001f",
                "error": "#ac3149",
                "background": "#faf9fc",
                "on-primary-fixed": "#3f3f3f",
                "surface-container-highest": "#e1e2e8",
                "inverse-surface": "#0d0e10",
                "on-error": "#fff7f7",
                "tertiary-fixed": "#fca3ae",
                "surface-container-lowest": "#ffffff",
                "secondary-dim": "#644586",
                "on-secondary-fixed-variant": "#6c4d8f",
                "tertiary-dim": "#823e48",
                "on-tertiary": "#fff7f7",
                "on-primary-fixed-variant": "#5c5b5b",
                "secondary": "#705193",
                "primary-fixed": "#e4e2e1",
                "surface-tint": "#5f5f5f",
                "on-tertiary-fixed": "#450e1a",
                "on-background": "#303337",
                "surface-container-low": "#f4f3f7",
                "primary-dim": "#535353",
                "primary-fixed-dim": "#d6d4d3",
                "surface-container": "#ededf2",
                "on-primary-container": "#525151",
                "outline": "#787b80",
                "on-secondary-container": "#624384",
                "secondary-fixed": "#efdbff",
                "primary": "#5f5f5f",
                "tertiary-container": "#fca3ae",
                "tertiary": "#904954",
                "on-primary": "#fbf8f8",
                "on-tertiary-container": "#61242f",
                "on-surface": "#303337",
                "inverse-on-surface": "#9c9d9f",
                "secondary-container": "#efdbff",
                "error-dim": "#770326"
        },
        "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
        },
        "fontFamily": {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Manrope"],
                "label": ["Manrope"]
        }
      },
    },
  }
