'use strict';
const crypto = require('crypto');
const prisma = require('../../services/dbService');
const logger = require('../../services/logger');
const { auditLogRepository } = require('../../repositories/index');

function generateOTP() {
    // crypto.randomInt is CSPRNG-backed — required for security-sensitive OTPs
    return crypto.randomInt(100000, 1000000).toString();
}

function hashOTP(otp) {
    return crypto.createHash('sha256').update(otp + 'sitam-otp-salt').digest('hex');
}

// Admin: list all exit passes with optional status filter
const getAll = async (req, res) => {
    try {
        const { status } = req.query;
        const where = status ? { status } : {};
        const passes = await prisma.exitPass.findMany({
            where,
            include: { student: { select: { name: true, roll: true, phone: true } } },
            orderBy: { createdAt: 'desc' }
        });
        res.json(passes);
    } catch (err) { 
        res.status(500).json({ error: 'Failed to fetch exit passes' }); 
    }
};

// Admin: approve a pass and generate OTP
const approve = async (req, res) => {
    try {
        const { id } = req.params;
        const pass = await prisma.exitPass.findUnique({ where: { id }, include: { student: true } });
        if (!pass) return res.status(404).json({ error: 'Exit pass not found' });
        if (pass.status !== 'PENDING') return res.status(400).json({ error: 'Pass is not in pending state' });

        const otp = generateOTP();
        const otpHash = hashOTP(otp);
        const otpExpiry = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours

        const updated = await prisma.exitPass.update({
            where: { id },
            data: { 
                status: 'APPROVED', 
                otpHash, 
                otpExpiry, 
                approvedAt: new Date(),
                approvedBy: req.admin.email
            }
        });

        // Notify student via FCM
        try {
            const firebaseService = require('../../services/firebaseService');
            const tokens = await prisma.fcmToken.findMany({ where: { studentId: pass.studentId } });
            if (tokens.length > 0) {
                await firebaseService.sendToTokens?.(
                    tokens.map(t => t.token),
                    'Exit Pass Approved',
                    'Your exit pass has been approved. Open the app to view your OTP.'
                );
            }
        } catch (_) {}

        // Log to AuditLogs
        await auditLogRepository.log(
            pass.studentId,
            'EXIT_PASS_APPROVED',
            `Exit pass for student ${pass.student.name} (${pass.student.roll}) approved by ${req.admin.email}`,
            req.admin.id,
            'INFO'
        );

        logger.info(`[ExitPass] Approved: ${id}, student: ${pass.student.name}, OTP generated by ${req.admin.email}`);
        res.json({ ...updated, otp });
    } catch (err) {
        logger.error('[ExitPass] Approve error:', err);
        res.status(500).json({ error: 'Failed to approve exit pass' });
    }
};

// Admin: reject a pass with optional reason
const reject = async (req, res) => {
    try {
        const { id } = req.params;
        const { reason } = req.body;
        const pass = await prisma.exitPass.findUnique({ where: { id }, include: { student: true } });
        if (!pass) return res.status(404).json({ error: 'Exit pass not found' });

        const updated = await prisma.exitPass.update({
            where: { id },
            data: { status: 'REJECTED', rejectionNote: reason || 'Rejected by admin' }
        });

        // Notify student
        try {
            const firebaseService = require('../../services/firebaseService');
            const tokens = await prisma.fcmToken.findMany({ where: { studentId: pass.studentId } });
            if (tokens.length > 0) {
                await firebaseService.sendToTokens?.(
                    tokens.map(t => t.token),
                    'Exit Pass Rejected',
                    `Your exit pass request was rejected. Reason: ${reason || 'Not specified'}`
                );
            }
        } catch (_) {}

        res.json(updated);
    } catch (err) { 
        res.status(500).json({ error: 'Failed to reject exit pass' }); 
    }
};

// Gate Step 1: Verify OTP and show details (does not mark it used yet)
const verifyOTP = async (req, res) => {
    try {
        const { otp } = req.body;
        if (!otp) return res.status(400).json({ error: 'OTP is required' });

        const otpHash = hashOTP(otp);
        const pass = await prisma.exitPass.findFirst({
            where: { otpHash },
            include: { student: { select: { name: true, roll: true, phone: true, branch: true, year: true, section: true } } }
        });

        if (!pass) {
            return res.status(400).json({ valid: false, error: 'Invalid OTP' });
        }

        // If the pass is approved but expired, update its status
        if (pass.status === 'APPROVED' && new Date() > pass.otpExpiry) {
            await prisma.exitPass.update({ where: { id: pass.id }, data: { status: 'EXPIRED' } });
            pass.status = 'EXPIRED';
        }

        res.json({
            valid: true,
            id: pass.id,
            status: pass.status, // 'APPROVED', 'USED', 'EXPIRED', 'REJECTED'
            student: pass.student,
            destination: pass.destination,
            reason: pass.reason,
            requestedDate: pass.requestedDate,
            approvedBy: pass.approvedBy,
            otpExpiry: pass.otpExpiry
        });
    } catch (err) { 
        res.status(500).json({ error: 'OTP verification failed' }); 
    }
};

// Gate Step 2: Mark Exit Pass as USED
const markUsed = async (req, res) => {
    try {
        const { id } = req.params;
        const pass = await prisma.exitPass.findUnique({
            where: { id },
            include: { student: true }
        });

        if (!pass) return res.status(404).json({ error: 'Exit pass not found' });
        if (pass.status !== 'APPROVED') {
            return res.status(400).json({ error: `Cannot mark pass as used. Current status is ${pass.status}` });
        }

        if (new Date() > pass.otpExpiry) {
            await prisma.exitPass.update({ where: { id: pass.id }, data: { status: 'EXPIRED' } });
            return res.status(400).json({ error: 'OTP has expired' });
        }

        const updated = await prisma.exitPass.update({
            where: { id },
            data: { 
                status: 'USED', 
                verifiedAt: new Date(),
                verifiedBy: req.admin.email
            }
        });

        // Log to AuditLogs
        await auditLogRepository.log(
            pass.studentId,
            'OTP_VERIFIED',
            `Exit pass for student ${pass.student.name} (${pass.student.roll}) marked USED by guard ${req.admin.email}`,
            req.admin.id,
            'INFO'
        );

        logger.info(`[ExitPass] Pass ${id} marked USED by guard ${req.admin.email}`);
        res.json({ success: true, pass: updated });
    } catch (err) {
        logger.error('[ExitPass] Mark used error:', err);
        res.status(500).json({ error: 'Failed to mark exit pass as used' });
    }
};

// Student: submit a new exit pass application
const apply = async (req, res) => {
    try {
        let studentId = req.session?.studentId || req.body.studentId;
        if (!studentId && req.session?.userId) {
            const student = await prisma.student.findUnique({ where: { userId: req.session.userId } });
            studentId = student?.id;
        }
        if (!studentId) return res.status(401).json({ error: 'Not authenticated' });

        const { reason, destination } = req.body;
        const requestedDate = req.body.requestedDate || req.body.requestDate;
        if (!reason || !destination || !requestedDate) {
            return res.status(400).json({ error: 'Reason, destination, and requested date are required' });
        }

        // Prevent duplicate pending requests
        const existing = await prisma.exitPass.findFirst({ where: { studentId, status: 'PENDING' } });
        if (existing) return res.status(400).json({ error: 'You already have a pending exit pass request' });

        const pass = await prisma.exitPass.create({
            data: { studentId, reason, destination, requestedDate, status: 'PENDING' }
        });
        res.status(201).json({ success: true, ...pass });
    } catch (err) { 
        res.status(500).json({ error: 'Failed to submit exit pass' }); 
    }
};

// Student: fetch own exit pass history
const getMyPasses = async (req, res) => {
    try {
        let studentId = req.session?.studentId;
        if (!studentId && req.session?.userId) {
            const student = await prisma.student.findUnique({ where: { userId: req.session.userId } });
            studentId = student?.id;
        }
        if (!studentId) return res.status(401).json({ error: 'Not authenticated' });

        const passes = await prisma.exitPass.findMany({
            where: { studentId },
            orderBy: { createdAt: 'desc' }
        });

        const filtered = passes.map(p => {
            const { otpHash, ...rest } = p;
            return rest;
        });

        res.json({ passes: filtered });
    } catch (err) { 
        res.status(500).json({ error: 'Failed to fetch exit passes' }); 
    }
};

module.exports = { getAll, approve, reject, verifyOTP, markUsed, apply, getMyPasses };
